<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.7.9 on win32)" generated="20210119 17:36:02.155" rpa="false">
<suite id="s1" name="OpenEmrProject" source="C:\robotic_framework\robot_workspace\OpenEmrProject">
<suite id="s1-s1" name="LoginSuite" source="C:\robotic_framework\robot_workspace\OpenEmrProject\LoginSuite">
<suite id="s1-s1-s1" name="Verify Invalid Credentials" source="C:\robotic_framework\robot_workspace\OpenEmrProject\LoginSuite\verify_invalid_credentials.robot">
<test id="s1-s1-s1-t1" name="TC1">
<status status="FAIL" starttime="20210119 17:36:03.159" endtime="20210119 17:36:03.161" critical="yes">Test case contains no keywords.</status>
</test>
<status status="FAIL" starttime="20210119 17:36:02.298" endtime="20210119 17:36:03.162"></status>
</suite>
<status status="FAIL" starttime="20210119 17:36:02.293" endtime="20210119 17:36:03.164"></status>
</suite>
<status status="FAIL" starttime="20210119 17:36:02.244" endtime="20210119 17:36:03.166"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="OpenEmrProject">OpenEmrProject</stat>
<stat pass="0" fail="1" id="s1-s1" name="LoginSuite">OpenEmrProject.LoginSuite</stat>
<stat pass="0" fail="1" id="s1-s1-s1" name="Verify Invalid Credentials">OpenEmrProject.LoginSuite.Verify Invalid Credentials</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210119 17:36:03.159" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: XLRDError: Excel xlsx file; not supported</msg>
</errors>
</robot>
